# Install pre-commit hooks via
# pre-commit install

exclude: >
    (?x)^(
      \.vscode/settings\.json|
      test.*\.md|
      test.*\.txt|
      test.*\.html|
      src/utility/bcm2xxx/bcm2835.*
    )$
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending
      args: ["--fix=lf"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.5
    hooks:
    - id: ruff
    - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    - id: mypy
