version: "0.2"
words:
  - anymeas
  - apidoc
  - apigen
  - armhf
  - baudrate
  - bndy
  - cirquepinnacle
  - cpack
  - cppreference
  - cpython
  - CROSSCOMPILING
  - datasheet
  - DCMAKE
  - Doherty
  - DPICO
  - DPINNACLE
  - DPYTHON
  - endforeach
  - ftime
  - gnueabihf
  - intellimouse
  - intersphinx
  - ldconfig
  - libcirquepinnacle
  - linenos
  - literalinclude
  - Makefiles
  - MOSI
  - Muxing
  - Ofast
  - pico
  - pinout
  - pkgs
  - postinst
  - postrm
  - println
  - pthread
  - pybind
  - pythonic
  - repr
  - seealso
  - shogo
  - sourcedir
  - SOVERSION
  - spidev
  - STREQUAL
  - toctree
  - trackpad
  - trackpads
  - venv
  - viewcode
