version: "0.2"
words:
  - adafruit
  - anymeas
  - apidoc
  - apigen
  - ARCHS
  - armhf
  - armv
  - ASIC
  - baudrate
  - bdist
  - binfmt
  - bndy
  - cibuildwheels
  - CIBW
  - cirquepinnacle
  - cpack
  - CPHA
  - cppreference
  - cpython
  - CROSSCOMPILING
  - cxxabiv
  - datasheet
  - DCMAKE
  - Doherty
  - DPICO
  - DPINNACLE
  - DPYTHON
  - eabi
  - endforeach
  - ftime
  - gnueabihf
  - gpiochip
  - intellimouse
  - intersphinx
  - itsybitsy
  - ldconfig
  - libcirquepinnacle
  - libnewlib
  - linenos
  - literalinclude
  - LSBFIRST
  - Makefiles
  - manylinux
  - MOSI
  - MSBFIRST
  - musllinux
  - Muxing
  - Ofast
  - pico
  - PIMORONI
  - pinout
  - pkgs
  - postinst
  - postrm
  - println
  - pthread
  - pybind
  - pypa
  - pythonic
  - qtpy
  - raspberrypi
  - repr
  - sdist
  - seealso
  - setuptools
  - shogo
  - sourcedir
  - SOVERSION
  - SPARFUN
  - Sparkfun
  - spidev
  - stddef
  - stdlib
  - STREQUAL
  - THINGPLUS
  - tinyusb
  - toctree
  - tonistiigi
  - trackpad
  - trackpads
  - venv
  - viewcode
