#ifndef CIRQUEPINNACLE_ARCH_COMMON_H_
#define CIRQUEPINNACLE_ARCH_COMMON_H_

#if defined(ARDUINO)
    #include <Arduino.h>
    #include <SPI.h>
    #include <Wire.h>

    #ifndef PINNACLE_SPI_SPEED
        // Default is the maximum supported SPI speed (13 MHz)
        #define PINNACLE_SPI_SPEED 13000000
    #endif

    // alias for SPI bus implementation
    #define _SPI SPIClass
    // alias for I2C bus implementation
    #define _I2C TwoWire

typedef uint8_t pinnacle_gpio_t;

    #define PINNACLE_SS_CTRL(pin, value) digitalWrite(pin, value)

    #define PINNACLE_USE_ARDUINO_API

#else
    // all other platforms/frameworks will be included via "utility/includes.h" file generated by CMake.
    // see src/cmake/auto_config_driver.cmake script for supported options (on linux)
    #include "utility/includes.h"
#endif

#ifndef PINNACLE_DEV_HW_DEBUG
    // a switch to expose a convenient function for HW debugging.
    #define PINNACLE_DEV_HW_DEBUG false
#endif

#endif // CIRQUEPINNACLE_ARCH_COMMON_H_
