name: Arduino

on:
  pull_request:
    branches: [master]
    paths:
      - ".github/workflows/build_arduino.yml"
      - "examples/**/*.ino"
      - "src/*.h"
      - "src/*.cpp"
  push:
    branches: [master]
    paths:
      - ".github/workflows/build_arduino.yml"
      - "examples/**/*.ino"

env:
  SKETCH_REPORTS_PATH: sketches-reports

jobs:
  check_formatting:
    uses: ./.github/workflows/cpp_lint.yaml
    with:
      extensions: 'ino'

  build:
    needs: check_formatting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fqbn:
          - "arduino:avr:uno"
          - "arduino:avr:mega"
          - "arduino:avr:leonardo"
          - "arduino:avr:micro"
          - "arduino:avr:mini"
          - "arduino:avr:pro"
          - "arduino:avr:atmegang"
          - "arduino:avr:unowifi"
          - "arduino:megaavr:uno2018"
          - "arduino:mbed:nano33ble"
          - "arduino:samd:mkrwifi1010"
          - "arduino:samd:nano_33_iot"
          - "arduino:samd:adafruit_circuitplayground_m0"
          # - "arduino:samd:tian"
        # By default, don't generate size deltas data.
        enable-deltas-report:
          - false
        # Generate size deltas data for these boards
        include:
          - fqbn: arduino:samd:mkrzero
            enable-deltas-report: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          fqbn: ${{ matrix.fqbn }}
          enable-deltas-report: ${{ matrix.enable-deltas-report }}
          sketches-report-path: ${{ env.SKETCH_REPORTS_PATH }}
          sketch-paths: |
            - examples/absolute_mode
            - examples/anymeas_mode
            - examples/relative_mode

      - name: sketch reports
        if: matrix.enable-deltas-report
        id: delta-report-name
        run: >-
          echo "report-name=${{ matrix.fqbn }}" | tr : - >> "$GITHUB_OUTPUT"

      # This step is needed to pass the size data to the report job
      - name: Upload sketches report to workflow artifact
        if: matrix.enable-deltas-report
        uses: actions/upload-artifact@v4
        with:
          name: arduino-deltas-${{ steps.delta-report-name.outputs.report-name }}
          path: ${{ env.SKETCH_REPORTS_PATH }}

  report_size_deltas:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download sketches reports artifact
        uses: actions/download-artifact@v4
        with:
          pattern: arduino-deltas-*
          path: ${{ env.SKETCH_REPORTS_PATH }}

      - uses: 2bndy5/report-size-deltas@update-comment
        with:
          sketches-reports-source: ${{ env.SKETCH_REPORTS_PATH }}
          update-comment: true
