name: Docs

on:
  pull_request:
    branches: [master]
    paths:
      - "src/CirquePinnacle.h"
      - "docs/**"
      - "examples/**/*.ino"
      - "examples/**/*.cpp"
      - ".github/workflows/build_docs.yml"
  push:
    branches: [master]
    paths:
      - "src/CirquePinnacle.h"
      - "docs/**"
      - "examples/**/*.ino"
      - "examples/**/*.cpp"
      - ".github/workflows/build_docs.yml"
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - uses: actions/checkout@v4

      - name: Install sphinx deps
        run: python -m pip install -r docs/requirements.txt

      - name: build docs with Sphinx
        working-directory: docs
        run: sphinx-build . _build/html

      - name: Save sphinx docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Cirque_Pinnacle_docs
          path: ${{ github.workspace }}/docs/_build/html
