name: Build Docs

on: [pull_request, push]

jobs:
  host-doxygen:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build doxy
      uses: mattnotmitt/doxygen-action@v1
      with:
          working-directory: './docs/'
          doxyfile-path: './Doxyfile'
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install Sphinx extensions
      run: pip install -r docs/requirements.txt
    - name: run Sphinx
      run: |
        cd docs
        sphinx-build -E -W . _build
